title = "Welcome to Klarity!"
output_dir = "public"
base_url = "https://kociumba.github.io/klarity/"
doc_dirs = ["docs"]
entry = "docs/main.md"
ignore_out = true

[visual]
theme = "rose-pine-moon"
use_spa = true

[visual.vars]
# bg_main = "#000"
# accent_primary = "#0CCAD8"

[dev]
port = 42069

[editor]
enable_editor = true
